set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR arm)
set(CMAKE_C_COMPILER_TARGET arm-none-eabi)

set(TOOLCHAIN arm-none-eabi_14.2.rel1-1)

file(GLOB TOOLCHAIN_CANDIDATES
	 LIST_DIRECTORIES true
	 CONFIGURE_DEPENDS
	 "/opt/arm-gnu-toolchain-*-${CMAKE_C_COMPILER_TARGET}/bin"
)

if(CMAKE_VERSION VERSION_GREATER_EQUAL "3.18")
    set(TOOLCHAIN_ORDER NATURAL)
else()
    set(TOOLCHAIN_ORDER STRING)
endif()

list(SORT TOOLCHAIN_CANDIDATES COMPARE ${TOOLCHAIN_ORDER} ORDER DESCENDING)

find_program(CMAKE_C_COMPILER
	NAMES ${CMAKE_C_COMPILER_TARGET}-gcc
	HINTS
		ENV TOOLCHAIN_BIN_DIR
		"$ENV{HOME}/${TOOLCHAIN}/bin"
		"/opt/${TOOLCHAIN}/bin"
		"/srv/${TOOLCHAIN}/bin"
		"/usr/local/${TOOLCHAIN}/bin"
		"${TOOLCHAIN_CANDIDATES}"
	DOC "Path to the ARM toolchain binaries"
)

if(NOT CMAKE_C_COMPILER)
	message(FATAL_ERROR "Could not find '${CMAKE_C_COMPILER_TARGET}' toolchain binaries. Please set TOOLCHAIN_BIN_DIR or add it to your system PATH.")
endif()

set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
