name: |
  Linux: Build with CMake and gcc

on: [push, pull_request]

# When a PR is updated, cancel the jobs from the previous version.
# Merges do not define head_ref, so use run_id to never cancel those
# jobs.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        container:
          - "ubuntu:20.04"
          - "ubuntu:22.04"
          - "ubuntu:24.04"
          - "ubuntu:26.04"
          - "ubuntu:rolling"
          - "debian:oldoldstable-slim"
          - "debian:oldstable-slim"
          - "debian:stable-slim"
          - "debian:testing-slim"
          - "debian:unstable-slim"
        build_type:
          - 'Debug'
          - 'Release'

    container:
      image: ${{ matrix.container }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Install required tools
      run: |
        apt update
        DEBIAN_FRONTEND='noninteractive' apt install -o APT::Install-Suggests=false -qy \
          cmake \
          gcc-arm-none-eabi \
          git \
          make \
          wget

    - name: Install newlib based toolchain (if required)
      if:
        matrix.container == 'debian:testing-slim' || matrix.container == 'debian:unstable-slim'
      run: |
        ./cmake/install-debian-gcc-arm-none-eabi
        echo "$PWD/arm-none-eabi_14.2.rel1-1/bin" >> ${GITHUB_PATH}

    - name: Verify Toolchain Installation
      run: |
        cmake --version
        arm-none-eabi-ld --version
        arm-none-eabi-gcc --version

    - name: Configure
      run: |
        cmake -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DCMAKE_TOOLCHAIN_FILE="cmake/arm-none-eabi-gcc.cmake" -B "build"

    - name: Build
      run: |
        cmake --build "build"

    - name: Show logs
      if: ${{ failure() }}
      run: |
        cat build/CMakeFiles/CMakeConfigureLog.yaml || true
