name: Build with CMake, Ninja and Arm GNU Toolchain

on: [push, pull_request]

# When a PR is updated, cancel the jobs from the previous version.
# Merges do not define head_ref, so use run_id to never cancel those
# jobs.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
        gcc:
          - 'latest'
          - '15.2.Rel1'
          - '14.3.Rel1'
          - '13.3.Rel1'
          - '12.3.Rel1'
          - '11.3.Rel1'
          - '10.3-2021.10'
          - '9-2020-q2'
          - '8-2019-q3'
          - '7-2018-q2'
          - '6-2017-q2'
        build_type:
          - 'Debug'
          - 'Release'
        include:
          - os: macos-latest
            gcc: 'latest'
            build_type: 'Debug'
          - os: macos-latest
            gcc: 'latest'
            build_type: 'Release'
          - os: windows-latest
            gcc: 'latest'
            build_type: 'Debug'
          - os: windows-latest
            gcc: 'latest'
            build_type: 'Release'
      fail-fast: false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Install Arm GNU Toolchain
      uses: carlosperate/arm-none-eabi-gcc-action@v1
      with:
        release: ${{ matrix.gcc }}

    - name: Verify Toolchain Installation
      run: |
        cmake --version
        ninja --version
        arm-none-eabi-ld --version
        arm-none-eabi-gcc --version

    - name: Configure
      run: |
        cmake -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DCMAKE_TOOLCHAIN_FILE="cmake/arm-none-eabi-gcc.cmake" -B "build" -G Ninja

    - name: Build
      run: |
        cmake --build "build"
