name: |
  Linux: Build with CMake and gcc

on: [push, pull_request]

env:
  toolchain: arm-none-eabi-gcc

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        release:
        - "ubuntu:20.04"
        - "ubuntu:22.04"
        - "ubuntu:24.04"
        - "ubuntu:26.04"
        - "ubuntu:rolling"
        - "debian:oldstable-slim"
        - "debian:stable-slim"
        - "debian:testing-slim"
        - "debian:unstable-slim"

    steps:
    - uses: actions/checkout@v6

    - name: Prepare ${{ matrix.release }} container
      run: |
        podman version
        podman run --name stable -di --userns=keep-id:uid=1000,gid=1000 -v "$PWD":/home -w /home ${{ matrix.release }} bash
        podman exec -i stable uname -a
        podman exec -i stable id
        podman exec -i -u root stable apt update
        podman exec -e DEBIAN_FRONTEND='noninteractive' -i -u root stable apt install -o APT::Install-Suggests=false -qy \
                clang \
                cmake \
                gcc-arm-none-eabi \
                git \
                make \
                wget

    - name: install newlib based toolchain
      if:
        matrix.release == 'debian:testing-slim' || matrix.release == 'debian:unstable-slim'
      run: |
        podman exec -i stable ./cmake/install-debian-gcc-arm-none-eabi

    - name: Verify Toolchain Installation
      run: |
        podman exec -i stable cmake --version
        podman exec -i stable arm-none-eabi-ld --version
        podman exec -i stable arm-none-eabi-gcc --version

    - name: Configure & Build Debug
      env:
        build_type: Debug
      run: |
        build="build-${{ env.toolchain }}-${{ env.build_type }}"
        podman exec -i stable cmake -DCMAKE_BUILD_TYPE=${{ env.build_type }} -DCMAKE_TOOLCHAIN_FILE="cmake/${{ env.toolchain }}.cmake" -B "${build}"
        podman exec -i stable cmake --build "${build}"

    - name: Configure & Build Release
      env:
        build_type: Release
      run: |
        build="build-${{ env.toolchain }}-${{ env.build_type }}"
        podman exec -i stable cmake -DCMAKE_BUILD_TYPE=${{ env.build_type }} -DCMAKE_TOOLCHAIN_FILE="cmake/${{ env.toolchain }}.cmake" -B "${build}"
        podman exec -i stable cmake --build "${build}"

    - name: Show logs
      if: ${{ failure() }}
      run: |
        for log in build-*/CMakeFiles/{CMakeOutput.log,CMakeConfigureLog.yaml}; do \
                if [ -e ${log} ]; then \
                        echo "---------------- ${log} ----------------"; \
                        cat ${log}; \
                fi; \
        done
