name: "Markdown link check"

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  push:
    branches: [ master ]
    paths:
      - .github/workflows/markdown-link.yml
      - '**.md'

  pull_request:
    branches: [ master ]
    paths:
      - .github/workflows/markdown-link.yml
      - '**.md'

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Create mlc_config.json
        run: |
          cat <<EOT >> mlc_config.json
          {
            "ignorePatterns": [
              {
                "pattern": "www.st.com/SLA0044"
              }
            ]
          }
          EOT

      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          config-file: 'mlc_config.json'
