name: PR

on: [ pull_request ]

jobs:
  cpp_style_check:
    runs-on: ubuntu-latest
    name: Check C Styling
    steps:
    - name: Checkout this commit
      uses: actions/checkout@v4
      with:
        fetch-depth: 2
    - name: uncrustify check
      uses: Daniel-Trevitz/uncrustify-check@v1
      with:
        configFile: 'uncrustify.cfg'
        checkedPaths: 'src;include'
